'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class JsDefault
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("lzy.JsDefault", GetType(JsDefault).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to result.StartBlock(&quot;Namespace Aggregates&quot;);
        '''result.StartBlock(&quot;Friend Class {0}&quot;, [data.TableName]);
        '''
        '''result.Comment(&quot;Skriv dine egene methoder for å hente data.. &quot;);
        '''
        '''result.Comment(&quot;Validering&quot;);
        '''_.each([&quot;ValidateCreateEntity&quot;, &quot;ValidateUpdateEntity&quot;, &quot;ValidateDeleteEntity&quot;], function (e) {
        '''    result.StartBlock(&quot;Private Sub {0}(o as Entities.{1})&quot;, [e, data.TableName]);
        '''    result.EndBlock(&quot;End Sub&quot;);
        '''});
        '''
        '''result.EndBlock(&quot;End Class&quot;);
        '''result.EndBlock(&quot;End Namespace&quot;);
        '''.
        '''</summary>
        Friend Shared ReadOnly Property Aggregate() As String
            Get
                Return ResourceManager.GetString("Aggregate", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to result.StartBlock(&quot;Namespace Aggregates&quot;);
        '''result.StartBlock(&quot;Partial Class {0}&quot;, [data.TableName]);
        '''result.WriteFormatLine(&quot;Inherits GenericBaseAggregate(Of {0}, {1})&quot;, [&quot;DataAccess.I&quot; + data.TableName, &quot;DataAccess.&quot; + data.TableName]);
        '''result.WriteLine(&quot;&quot;);
        '''
        '''//GetInstance
        '''result.Write(&quot;Public Function GetInstance(&quot;)
        '''_.each(data.Table.Columns,function(c,i) {
        '''    if(c.Identity) {
        '''        if(i)result.write(&quot;,&quot;);
        '''        result.WriteFormat(&quot;{0}{1} As {2}&quot;,[Utils.toParamName(data.TableName),c.Name,c. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Aggregate_Partial() As String
            Get
                Return ResourceManager.GetString("Aggregate_Partial", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to result.StartBlock(&quot;Namespace DataAccess&quot;, []);
        '''result.StartBlock(&quot;Friend Class {0}&quot;, [data.TableName]);
        '''    
        '''
        '''result.EndBlock(&quot;End Class&quot;);
        '''result.EndBlock(&quot;End Namespace&quot;);
        '''.
        '''</summary>
        Friend Shared ReadOnly Property DataAccess() As String
            Get
                Return ResourceManager.GetString("DataAccess", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to //Her kommer det en beskrivelse av js variabler som man skal ha tilgang til.
        '''
        '''var identity = _.filter(data.Table.Columns, function (e) { return e.Identity });
        '''
        '''result.StartBlock(&quot;Namespace DataAccess&quot;)
        '''
        '''result.StartBlock(&quot;Partial Class {0}&quot;, [data.TableName]);
        '''result.WriteFormatLine(&quot;Implements I{0}&quot;,[data.TableName]);
        '''//GetEntity
        '''result.StartBlock(&quot;Public Function GetEntity(ByVal sourceName As String, ByRef o As Entities.{0}) As Boolean Implements I{0}.GetEntity&quot;, [data.TableName]);
        '''result.WriteL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DataAccess_Partial() As String
            Get
                Return ResourceManager.GetString("DataAccess_Partial", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to result.StartBlock(&quot;Namespace Entities&quot;);
        '''result.StartBlock(&quot;Public Class {0}&quot;, [data.Table.Name]);
        '''result.WriteComment(&quot;Har kan du legge inn dine spessielle ting for denne klassen&quot;);
        '''
        '''result.EndBlock(&quot;End Class&quot;);
        '''result.EndBlock(&quot;End Namespace&quot;);
        '''.
        '''</summary>
        Friend Shared ReadOnly Property Entity() As String
            Get
                Return ResourceManager.GetString("Entity", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to result.StartBlock(&quot;Namespace Entities&quot;);
        '''result.StartBlock(&quot;Public Class {0}Collection&quot;, [data.TableName]);
        '''result.WriteFormatLine(&quot;Inherits LazyList(Of {0})&quot;, [data.TableName]);
        '''result.Comment(&quot;Basic list for your object&quot;);
        '''result.EndBlock(&quot;End Class&quot;);
        '''result.EndBlock(&quot;End Namespace&quot;);
        '''.
        '''</summary>
        Friend Shared ReadOnly Property Entity_Collection() As String
            Get
                Return ResourceManager.GetString("Entity_Collection", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to result.StartBlock(&quot;Namespace Entities&quot;);
        '''result.StartBlock(&quot;Partial Class {0}&quot;, [data.Table.Name])
        '''result.WriteLine(&quot;Inherits LazyBaseclass&quot;)
        '''
        '''//Field property
        '''result.WriteReadOnlyProp(&quot;Fields&quot;, &quot;String()&quot;, &quot;{&quot; + _.map(data.Table.Columns, function (o) { return &apos;&quot;&apos; + o.Name + &apos;&quot;&apos; }).join(&apos;,&apos;) + &quot;}&quot;, &quot;Overrides&quot;);
        '''
        '''//Private variables
        '''_.each(data.Table.Columns, function (o) {
        '''    result.WriteFormatLine(&quot;Private _{0} as {1}{2}&quot;, [o.ParamName, o.NetRuntimeType, o.Nullable &amp;&amp; o.IsValueType ? &apos;?&apos; : &apos;&apos;])
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Entity_Partial() As String
            Get
                Return ResourceManager.GetString("Entity_Partial", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to //
        '''result.StartBlock(&quot;Namespace DataAccess&quot;,[]);
        '''result.StartBlock(&quot;Public Interface I{0}&quot;,[data.TableName]);
        '''
        '''result.WriteFormatLine(&quot;Function GetEntity(ByVal sourceName As String, ByRef o As Entities.{0}) As Boolean&quot;, [data.TableName]);
        '''result.WriteFormatLine(&quot;Function GetAll(ByVal sourceName As String, ByRef o As Entities.{0}Collection) As Boolean&quot;, [data.TableName]);
        '''result.WriteFormatLine(&quot;Function Create(ByVal sourceName As String, ByRef o As Entities.{0}) As Boolean&quot;, [data.TableName]);
        '''result [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property IDataAccess() As String
            Get
                Return ResourceManager.GetString("IDataAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //Her kommer det en beskrivelse av js variabler som man skal ha tilgang til..
        '''</summary>
        Friend Shared ReadOnly Property Standard() As String
            Get
                Return ResourceManager.GetString("Standard", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
