'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class XSLTDefault
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("lzy.XSLTDefault", GetType(XSLTDefault).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''  &lt;xsl:output method=&quot;text&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
        '''
        '''  &lt;xsl:template match=&quot;/TableSettings/DatabaseInfoName&quot; /&gt;
        '''  &lt;xsl:template match=&quot;/TableSettings/TableName&quot; /&gt;
        '''  &lt;xsl:template match=&quot;/TableSettings/FilePath&quot; /&gt;
        '''
        '''  &lt;xsl:template match=&quot;/TableSettings/Table&quot;&gt;
        '''
        '''    Public Class &lt;xsl:value-of select=&quot;Name&quot;/&gt;
        '''
        '''    
        '''    End Class
        '''
        '''
        '''  &lt;/xsl:te [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Entity() As String
            Get
                Return ResourceManager.GetString("Entity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''  &lt;xsl:output method=&quot;text&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
        '''
        '''  &lt;xsl:template match=&quot;/TableSettings/DatabaseInfoName&quot; /&gt;
        '''  &lt;xsl:template match=&quot;/TableSettings/TableName&quot; /&gt;
        '''  &lt;xsl:template match=&quot;/TableSettings/FilePath&quot; /&gt;
        '''
        '''  &lt;xsl:template match=&quot;/TableSettings/Table&quot;&gt;
        '''
        '''    Public Partial Class &lt;xsl:value-of select=&quot;Name&quot;/&gt;
        '''
        '''    &lt;xsl:for-each select=&quot;C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property EntityPartial() As String
            Get
                Return ResourceManager.GetString("EntityPartial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''
        '''&lt;xsl:output method=&quot;text&quot; encoding=&quot;UTF-8&quot; indent=&quot;no&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
        '''
        '''  &lt;xsl:template match=&quot;/TableSettings/DatabaseInfoName&quot; /&gt;
        '''  &lt;xsl:template match=&quot;/TableSettings/TableName&quot; /&gt;
        '''  &lt;xsl:template match=&quot;/TableSettings/FilePath&quot; /&gt;
        '''  &lt;xsl:template match=&quot;/TableSettings/Table&quot;&gt;
        '''  
        '''
        '''&lt;/xsl:stylesheet&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Standard() As String
            Get
                Return ResourceManager.GetString("Standard", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
